version: "3.9"

services:
  rust_indexer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgresqltimescale/eth_indexer
      REDIS_URL: redis://cacheredis:6379/0
      CONTRACT_ADDRESS: 0x21b06BEc125803635f0a9221655E731f6b0DB478
      START_BLOCK: 8096310
    command: ["./indexer"]
    depends_on:
      - postgresqltimescale
      - cacheredis

  rust_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgresqltimescale/eth_indexer
      REDIS_URL: redis://cacheredis:6379/0
    command: ["./api"]
    depends_on:
      - postgresqltimescale
      - cacheredis
    ports:
      - "3000:3000"

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgresqltimescale/eth_indexer
    depends_on:
      - postgresqltimescale

  postgresqltimescale:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  cacheredis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  timescale-data:
  redis-data:

